CREATE TABLE IF NOT EXISTS BODY (
  BODY_TYPE VARCHAR (255) NOT NULL, 
  PRIMARY KEY (BODY_TYPE)
);
CREATE TABLE IF NOT EXISTS BRAND (
  BRAND_NAME VARCHAR (255) NOT NULL, 
  PRIMARY KEY (BRAND_NAME)
);
CREATE TABLE IF NOT EXISTS COLOR (
  COLOR_NAME VARCHAR (255) NOT NULL, 
  PRIMARY KEY (COLOR_NAME)
);
CREATE TABLE IF NOT EXISTS DEPARTMENT (
  DEP_CODE INT NOT NULL, 
  DEP_NAME VARCHAR (255), 
  PRIMARY KEY (DEP_CODE)
);
CREATE TABLE IF NOT EXISTS FUEL (
  FUEL_TYPE VARCHAR (255) NOT NULL, 
  PRIMARY KEY (FUEL_TYPE)
);
CREATE TABLE IF NOT EXISTS KIND (
  KIND_NAME VARCHAR (255) NOT NULL, 
  PRIMARY KEY (KIND_NAME)
);
CREATE TABLE IF NOT EXISTS MODEL (
  MODEL_NAME VARCHAR (255) NOT NULL, 
  PRIMARY KEY (MODEL_NAME)
);
CREATE TABLE IF NOT EXISTS OPERATION (
  OP_CODE INT NOT NULL, 
  OP_NAME VARCHAR (255), 
  PRIMARY KEY (OP_CODE)
);
CREATE TABLE IF NOT EXISTS PURPOSE (
  PURPOSE_NAME VARCHAR (255) NOT NULL, 
  PRIMARY KEY (PURPOSE_NAME)
);
CREATE TABLE IF NOT EXISTS VEHICLE (
  VEHICLE_ID SERIAL NOT NULL, 
  BRAND_NAME VARCHAR (255) NOT NULL, 
  MODEL_NAME VARCHAR (255), 
  BODY_TYPE VARCHAR (255), 
  KIND_NAME VARCHAR (255), 
  FUEL_TYPE VARCHAR (255), 
  PURPOSE_NAME VARCHAR (255), 
  ENGINE_CAPACITY INT, 
  MAKE_YEAR INT, 
  OWN_WEIGHT INT, 
  TOTAL_WEIGHT INT, 
  PRIMARY KEY (VEHICLE_ID), 
  CONSTRAINT FK_BRAND FOREIGN KEY (BRAND_NAME) REFERENCES BRAND (BRAND_NAME), 
  CONSTRAINT FK_MODEL FOREIGN KEY (MODEL_NAME) REFERENCES MODEL (MODEL_NAME), 
  CONSTRAINT FK_BODY FOREIGN KEY (BODY_TYPE) REFERENCES BODY (BODY_TYPE), 
  CONSTRAINT FK_KIND FOREIGN KEY (KIND_NAME) REFERENCES KIND (KIND_NAME), 
  CONSTRAINT FK_FUEL FOREIGN KEY (FUEL_TYPE) REFERENCES FUEL (FUEL_TYPE), 
  CONSTRAINT FK_PURPOSE FOREIGN KEY (PURPOSE_NAME) REFERENCES PURPOSE (PURPOSE_NAME)
);
CREATE TABLE IF NOT EXISTS REGISTRATION (
  REG_ID SERIAL NOT NULL, 
  VEHICLE_ID INT NOT NULL, 
  PERSON_TYPE VARCHAR (2), 
  PERSON_REG_ADDRESS VARCHAR (255), 
  REG_DATE DATE, 
  REG_NUMBER VARCHAR (15), 
  VIN_NUMBER VARCHAR (255), 
  COLOR_NAME VARCHAR (255), 
  OP_CODE INT NOT NULL, 
  DEP_CODE INT NOT NULL, 
  PRIMARY KEY (REG_ID), 
  CONSTRAINT FK_VEHICLE_ID FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE (VEHICLE_ID), 
  CONSTRAINT FK_COLOR FOREIGN KEY (COLOR_NAME) REFERENCES COLOR (COLOR_NAME), 
  CONSTRAINT FK_OP_CODE FOREIGN KEY (OP_CODE) REFERENCES OPERATION (OP_CODE), 
  CONSTRAINT FK_DEP_CODE FOREIGN KEY (DEP_CODE) REFERENCES DEPARTMENT (DEP_CODE)
);